dataset:
  augment_feature: []
  augment_feature_dims:
  - 0
  augment_feature_repr: position
  augment_label: ''
  augment_label_dims: 0
  format: PyG
  name: TU_PROTEINS
  split:
  - 0.8
  - 0.2
  task: graph
  task_type: classification
  transductive: false
  transform: none
gnn:
  act: prelu
  agg: mean
  batchnorm: true
  dim_inner: 209
  dropout: 0.0
  layer_type: generalconv
  layers_mp: 2
  layers_post_mp: 2
  layers_pre_mp: 2
  normalize_adj: false
  stage_type: skipsum
model:
  edge_decoding: dot
  graph_pooling: add
  loss_fun: cross_entropy
  type: gnn
optim:
  base_lr: 0.01
  max_epoch: 400
  optimizer: adam
out_dir: results/example_grid_example
train:
  batch_size: 32
  ckpt_period: 100
  eval_period: 20
